dataset: "somethingcmn"
dataset_base_path: ""
method: ""
train_n_way: 5
test_n_way: 5
n_query: 1
n_shot: 1
num_gpus: 3
train_aug: True
work_dir: "./workspace/"
num_segments: 8
train_episode: 1000
test_episode: 10000
eval_episode: 1000
test_model: False
load_weights: False
checkpoint: ""
start_epoch: 0
stop_epoch: 10
warm_up_epoch: 8
text_depth: 2
lr: 0.001
message: "Null"
