dataset: ""
dataset_base_path: ""
method: "taskadapter"
train_n_way: 5
test_n_way: 5
n_query: 1
n_shot: 1
num_gpus: 3
train_aug: True
work_dir: "./workspace/"
num_segments: 8
val_freq: 30
train_episode: 200
test_episode: 10000
eval_episode: 1000
test_model: False
load_weights: False
checkpoint: ""
save_freq: 100
start_epoch: 0
stop_epoch: 10
warm_up_epoch: 5
text_depth: 8
lr: 0.001
message: "Null"
